### ISSUE TITLE
Excellent articles! Repost request.

### ISSUE THREAD

**Issue by Amaindex** [liuhangbin/liuhangbin.github.io#16]
Liu, I am very grateful for your article. I have learned a lot from it😀👍.
But there seems to be no Chinese version, can I repost them and create a Chinese version  for education purpose?
**I will meticulously note the source.**

**Comment by liuhangbin** [comment]
你好，你说的repost 是指 report 到哪里啊？ 因为我的文章大部分都是计算机类的。里面专业词汇太多了，懒得中英文来会切换，所以写着写着就干脆全英文了。

**Comment by Amaindex** [comment]
感谢您能用中文回复我 😁
仅用于高校内部的学术交流或放在个人博客上，不会用于任何商业目的。

**Comment by liuhangbin** [comment]
好的，标明原出处就可以了。
